import { defineTool } from '@tool/type';
import {
  FlowNodeInputTypeEnum,
  FlowNodeOutputTypeEnum,
  WorkflowIOValueTypeEnum
} from '@tool/type/ipolloos';
import { listTemplateOptions } from '../../lib/templates';

export default defineTool({
  name: {
    'zh-CN': 'HTML Anything · 生成发布页',
    en: 'HTML Anything · generate page'
  },
  description: {
    'zh-CN':
      '发布上游 AI 大脑生成的完整单文件 HTML，支持网站、PPT、电子书、研究报告、白皮书，并默认发布到 OSS 公网域名。',
    en: 'Publish complete single-file HTML generated by the upstream AI brain to OSS.'
  },
  toolDescription:
    '该工具不调用模型、不生成内容、不需要 ai_app_key。必须先由上游 AI 大脑根据用户需求选择模板类别并生成完整单文件 HTML，然后把完整 HTML 源码放入 content 调用本工具。本工具只负责校验 HTML、按模板类别注入运行层/导出/目录等确定性能力，并发布到 OSS 或返回 raw_html。分类选择必须优先服从用户最终交付形态：PPT/幻灯片/演示文稿/deck 选 slides；电子书/书籍/研究报告/白皮书/论文/深度专题选 publication/book/research；网站/官网/落地页/原型选 web/prototype；数据看板选 dashboard；移动端 App/单屏界面选 mobile；小红书/海报/卡片按 card/poster。content 必须包含真实 <html><head>...</head><body>...</body></html>，不要传原始需求、Markdown 或说明文字。',
  versionList: [
    {
      value: '1.2.19',
      description:
        'Keep publication TOC on desktop without overlapping main content while preserving mobile drawer TOC, PDF export, and gallery metadata',
      inputs: [
        {
          key: 'template_id',
          label: '模板选择',
          valueType: WorkflowIOValueTypeEnum.string,
          renderTypeList: [FlowNodeInputTypeEnum.reference, FlowNodeInputTypeEnum.select],
          required: true,
          defaultValue: 'auto',
          list: listTemplateOptions(),
          selectorConfig: {
            variant: 'gallery',
            title: '选择 HTML Anything 模板',
            description: '用于标记/增强页面类型；HTML 内容应由上游 AI 大脑先生成完成。',
            searchPlaceholder: '搜索模板名称、ID、类型、场景或标签',
            groupBy: 'category',
            allowAuto: true,
            autoValue: 'auto',
            autoLabel: 'AI 自动选择'
          },
          toolDescription:
            '模板 ID 决定插件后续注入哪一类运行机制，不能随便固定成某个模板。上游 AI 大脑必须先判断用户要的最终交付形态，再选择模板：PPT/幻灯片/deck 选 slides 类；电子书/书籍选 book-editorial；行业/课题/趋势/咨询研究选 research-report；学术/课程/会议/期刊论文选 academic-paper；企业方案/技术架构/商业观点白皮书选 whitepaper-html；杂志专题/深度报道选 magazine-feature；官网/落地页选 saas-landing；产品原型选 prototype-web；数据看板/经营分析选 dashboard/data-report；移动 App 页面选 mobile-app；小红书选 card-xiaohongshu；海报选 poster-hero。视频不是 HTML 页面模板，请改用 HyperFrames 视频插件。若用户明确指定形态，必须优先服从用户形态而不是内容题材。'
        },
        {
          key: 'content',
          label: '完整 HTML',
          valueType: WorkflowIOValueTypeEnum.string,
          renderTypeList: [FlowNodeInputTypeEnum.reference, FlowNodeInputTypeEnum.textarea],
          required: true,
          toolDescription:
            '上游 AI 大脑已经生成完成的完整单文件 HTML 源码。必须包含 <!DOCTYPE html> 或 <html>、<head>、<body> 和 </html>。不要传原始用户需求、Markdown、CSV、JSON、SQL 或“请生成页面”的说明文字；这些应由上游 AI 大脑在调用工具前完成推理和生成。'
        },
        {
          key: 'format',
          label: '输入格式',
          valueType: WorkflowIOValueTypeEnum.string,
          renderTypeList: [FlowNodeInputTypeEnum.reference, FlowNodeInputTypeEnum.select],
          defaultValue: 'html',
          list: [
            { label: 'text', value: 'text' },
            { label: 'markdown', value: 'markdown' },
            { label: 'csv', value: 'csv' },
            { label: 'json', value: 'json' },
            { label: 'sql', value: 'sql' },
            { label: 'html', value: 'html' }
          ],
          toolDescription: '兼容字段。当前工具不调用 AI；建议传 html。'
        },
        {
          key: 'language',
          label: '输出语言',
          valueType: WorkflowIOValueTypeEnum.string,
          renderTypeList: [FlowNodeInputTypeEnum.reference, FlowNodeInputTypeEnum.select],
          defaultValue: 'zh-CN',
          list: [
            { label: '中文', value: 'zh-CN' },
            { label: 'English', value: 'en' },
            { label: '日本語', value: 'ja' },
            { label: '跟随内容', value: 'auto' }
          ],
          toolDescription: '生成页面的主要语言。'
        },
        {
          key: 'extra_requirements',
          label: '额外要求',
          valueType: WorkflowIOValueTypeEnum.string,
          renderTypeList: [FlowNodeInputTypeEnum.reference, FlowNodeInputTypeEnum.textarea],
          toolDescription:
            '兼容字段。建议写入原始用户意图、选择模板的理由、最终交付形态和关键约束，便于工具做模板类别兜底校验；当前工具不会据此再调用 AI。不要在这里填写密钥。'
        },
        {
          key: 'edit_from_html',
          label: '已有 HTML（可选）',
          valueType: WorkflowIOValueTypeEnum.string,
          renderTypeList: [FlowNodeInputTypeEnum.reference, FlowNodeInputTypeEnum.textarea],
          toolDescription:
            '兼容字段。编辑也应由上游 AI 大脑先完成，content 传最终 HTML。填写时必须同时填写 edit_from_content。'
        },
        {
          key: 'edit_from_content',
          label: '旧内容（可选）',
          valueType: WorkflowIOValueTypeEnum.string,
          renderTypeList: [FlowNodeInputTypeEnum.reference, FlowNodeInputTypeEnum.textarea],
          toolDescription:
            '兼容字段。已有 HTML 对应的旧内容。填写时必须同时填写 edit_from_html；工具不会再调用 AI 做编辑。'
        },
        {
          key: 'page_output_mode',
          label: '页面输出模式',
          description:
            '自动发布：按现有 HTML 页面上传方式发布到 OSS 公网域名；raw_html：仅返回 HTML。',
          valueType: WorkflowIOValueTypeEnum.string,
          renderTypeList: [FlowNodeInputTypeEnum.select],
          defaultValue: 'auto_publish',
          list: [
            { label: '自动发布到 OSS', value: 'auto_publish' },
            { label: '仅返回 HTML', value: 'raw_html' }
          ],
          toolDescription:
            '一般保持 auto_publish；平台会上传 page_html 并写回 page_url。只有调试或下游自行托管时才选 raw_html。'
        }
      ],
      outputs: [
        {
          valueType: WorkflowIOValueTypeEnum.string,
          key: 'page_html',
          label: '页面 HTML',
          description: '完整单文件 HTML。仅 raw_html 模式返回；auto_publish 模式只返回 page_url。'
        },
        {
          valueType: WorkflowIOValueTypeEnum.string,
          key: 'page_url',
          label: '页面公开链接',
          description: 'auto_publish 后由平台写入。'
        },
        {
          valueType: WorkflowIOValueTypeEnum.string,
          key: 'full_html',
          label: '完整 HTML 文档（兼容字段，仅 raw_html 模式返回）'
        },
        {
          valueType: WorkflowIOValueTypeEnum.string,
          key: 'template_id',
          label: '模板 ID'
        },
        {
          valueType: WorkflowIOValueTypeEnum.string,
          key: 'template_name',
          label: '模板名称'
        },
        {
          valueType: WorkflowIOValueTypeEnum.string,
          key: 'summary',
          label: '摘要'
        },
        {
          type: FlowNodeOutputTypeEnum.error,
          valueType: WorkflowIOValueTypeEnum.string,
          key: 'system_error',
          label: '错误信息'
        }
      ]
    }
  ]
});
