import { defineToolSet } from '@tool/type';
import { ToolTagEnum } from '@tool/type/tags';

export default defineToolSet({
  tags: [ToolTagEnum.enum.productivity, ToolTagEnum.enum.multimodal],
  name: {
    'zh-CN': 'HTML Anything 生成器',
    en: 'HTML Anything generator'
  },
  description: {
    'zh-CN': '发布 LangGraph 大脑按 html-anything 模板生成的完整单文件 HTML。',
    en: 'Publish complete single-file HTML generated by the LangGraph agent with html-anything templates.'
  },
  toolDescription:
    '工具 html_anything_page 不调用模型、不持有独立 AI Key。LangGraph/Agent 大脑负责反复推理、模板选择和完整 HTML 生成；本插件只校验 content 中的完整 HTML、注入通用运行层/导出能力，并默认发布到 OSS 公网域名返回 page_url。只有 raw_html 模式返回 page_html/full_html。'
});
