import { defineToolSet } from '@tool/type';
import { ToolTagEnum } from '@tool/type/tags';

export default defineToolSet({
  tags: [ToolTagEnum.enum.multimodal, ToolTagEnum.enum.productivity],
  name: {
    'zh-CN': '移动端 AI 服务生成器 V4',
    en: 'Mobile AI service generator V4'
  },
  description: {
    'zh-CN':
      '发布上游 AI 大脑生成的移动端优先 AI 服务 HTML：短片、视频工具、测算、小游戏、表单和体验式应用均可。',
    en: 'Publish mobile-first AI service HTML generated by the上游 AI 大脑agent: short-video concepts, video tools, divination apps, mini games, forms, and interactive experiences.'
  },
  toolDescription:
    'UPSTREAM_AI_RUNTIME_BRIDGE：该工具不调用模型、不持有独立 AI Key。上游 AI 大脑负责需求理解、反复推理、完整移动端 HTML 生成；工具 mobile_ai_html_app 只校验 generated_html 中的完整 HTML，并注入 iPolloOS Runtime 调用桥。页面内 AI 回复、搜索、语音、图像、视频和数据库动作应通过平台 Runtime 回到上游 AI 大脑执行。'
});
