import { defineToolSet } from '@tool/type';
import { ToolTagEnum } from '@tool/type/tags';

export default defineToolSet({
  tags: [ToolTagEnum.enum.multimodal, ToolTagEnum.enum.productivity],
  name: {
    'zh-CN': '移动端 AI 服务生成器',
    en: 'Mobile AI service generator'
  },
  description: {
    'zh-CN':
      '发布上游 AI 大脑生成的移动端优先 AI 服务 HTML：短片、视频工具、测算、小游戏、表单和体验式应用均可。',
    en: 'Publish mobile-first AI service HTML generated by the上游 AI 大脑agent: short-video concepts, video tools, divination apps, mini games, forms, and interactive experiences.'
  },
  toolDescription:
    '该工具不调用模型、不持有独立 AI Key。上游 AI 大脑负责需求理解、反复推理、完整移动端 HTML 生成；工具 mobile_ai_html_app 只校验 generated_html 中的完整 HTML，并返回 page_html/page_cover。'
});
